// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1f-OZy7v9F4SP9_7oKLdG7DKuS-5L1zY',
    appId: '1:924821486500:web:39467ebd07ea5a65f2df31',
    messagingSenderId: '924821486500',
    projectId: 'qr-attendance-16860',
    authDomain: 'qr-attendance-16860.firebaseapp.com',
    databaseURL: 'https://qr-attendance-16860-default-rtdb.firebaseio.com',
    storageBucket: 'qr-attendance-16860.firebasestorage.app',
    measurementId: 'G-8QF64DYCM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc_elEO02WoKIpC_AVrAQV_BhxtFqZcuA',
    appId: '1:924821486500:android:56ca8cadb036f39ff2df31',
    messagingSenderId: '924821486500',
    projectId: 'qr-attendance-16860',
    databaseURL: 'https://qr-attendance-16860-default-rtdb.firebaseio.com',
    storageBucket: 'qr-attendance-16860.firebasestorage.app',
  );
}
